/* Taking a preset dump apart.
 *
 * A transcription of ThereMaxi::Preset::import_data and the value_import
 * methods it dispatches to. protocol/golden.json was generated by that code and
 * tests/test_preset_decode.c replays it through this, so the two have to agree
 * value for value.
 *
 * Copyright (C) 2017 Peter Niebling and contributors. GPL-3.0-or-later.
 */

#include "theremini/protocol.h"

#include <math.h>
#include <string.h>

/* The perl unpacks with 'S'/'s', which are native endian. The Theremini sends
 * little endian and every machine this has ever run on is little endian, so
 * that is what the format actually is. Read it explicitly rather than by
 * accident. */
static uint16_t read_u16(const uint8_t *p)
{
	return (uint16_t)((uint16_t)p[0] | (uint16_t)((uint16_t)p[1] << 8));
}

static int16_t read_s16(const uint8_t *p)
{
	return (int16_t)read_u16(p);
}

/* sprintf '%.<digits>f' in perl, without going through a string - and without
 * the locale trouble that made the perl need tr/,/./ in the first place. */
static double round_to(double value, int digits)
{
	double scale = 1.0;
	for (int i = 0; i < digits; i++) {
		scale *= 10.0;
	}
	return round(value * scale) / scale;
}

static void import_numeric(const theremini_param *param, double raw,
                           theremini_value *out)
{
	/* NaN passes every comparison, so it would slip through the clamping
	 * below. It is what made a cutoff word under 15 corrupt a whole library
	 * in the perl version. */
	if (isnan(raw)) {
		raw = param->min;
	}

	raw = round_to(raw, param->digits);

	if (raw < param->min) {
		raw = param->min;
	}
	if (raw > param->max) {
		raw = param->max;
	}

	out->number = raw;
}

static void import_cutoff(const theremini_param *param, double raw,
                          theremini_value *out)
{
	/* ((raw - 15) / 12500) ** (1/3) * 100, with a cube root that accepts a
	 * negative argument. The clamp in import_numeric then takes it to the
	 * minimum, which is what the curve means down there. */
	const double x = (raw - 15.0) / 12500.0;
	const double root = x < 0 ? -cbrt(-x) : cbrt(x);

	import_numeric(param, root * 100.0, out);
}

static void import_text(const uint8_t *data, size_t size, size_t offset,
                        theremini_pack pack, theremini_value *out)
{
	char raw[THEREMINI_TEXT_MAX];
	size_t n = 0;

	memset(raw, 0, sizeof raw);

	for (size_t i = 0; i < 13 && n < sizeof raw - 1; i++) {
		/* padded names put a filler byte after every character */
		const size_t at = offset + (pack == THEREMINI_PACK_TEXT_PADDED ? i * 2 : i);
		if (at >= size) {
			break;
		}
		if (data[at] == '\0') {
			break;
		}
		raw[n++] = (char)data[at];
	}
	raw[n] = '\0';

	/* trim both ends, as name::value_import does */
	size_t start = 0;
	while (raw[start] == ' ' || raw[start] == '\t') {
		start++;
	}
	size_t end = strlen(raw + start);
	while (end > 0 && (raw[start + end - 1] == ' ' || raw[start + end - 1] == '\t')) {
		end--;
	}

	if (end > THEREMINI_TEXT_MAX - 1) {
		end = THEREMINI_TEXT_MAX - 1;
	}
	memcpy(out->text, raw + start, end);
	out->text[end] = '\0';
}

bool theremini_preset_decode(const uint8_t *data, size_t size, int number,
                             theremini_preset *out)
{
	size_t offset_count;
	const theremini_offset *offsets = theremini_offsets(&offset_count);
	size_t param_count;
	const theremini_param *params = theremini_params(&param_count);

	if (!data || !out || param_count > THEREMINI_PARAM_MAX) {
		return false;
	}

	memset(out, 0, sizeof *out);

	/* Two offsets feed the waveform, and its import adds them up. Nothing
	 * else takes more than one, so a running total per parameter is enough. */
	double raw[THEREMINI_PARAM_MAX];
	bool seen[THEREMINI_PARAM_MAX];
	memset(raw, 0, sizeof raw);
	memset(seen, 0, sizeof seen);

	for (size_t i = 0; i < offset_count; i++) {
		const theremini_offset *o = &offsets[i];
		const theremini_param *p = theremini_param_by_id(o->param_id);

		if (!p) {
			continue;
		}
		const size_t index = theremini_param_index(p);

		if (o->pack == THEREMINI_PACK_TEXT ||
		    o->pack == THEREMINI_PACK_TEXT_PADDED) {
			if (o->offset >= size) {
				return false;
			}
			import_text(data, size, o->offset, o->pack, &out->values[index]);
			out->values[index].present = true;
			continue;
		}

		if (o->offset + 2 > size) {
			return false;
		}

		double value = o->pack == THEREMINI_PACK_S16
		               ? (double)read_s16(data + o->offset)
		               : (double)read_u16(data + o->offset);

		if (o->divisor != 0) {
			value /= o->divisor;
		}

		raw[index] += value;
		seen[index] = true;
	}

	for (size_t i = 0; i < param_count; i++) {
		if (!seen[i]) {
			continue;
		}
		theremini_value *v = &out->values[i];
		v->present = true;

		switch (params[i].import) {
		case THEREMINI_IMPORT_NUMERIC:
			import_numeric(&params[i], raw[i], v);
			break;
		case THEREMINI_IMPORT_CUTOFF:
			import_cutoff(&params[i], raw[i], v);
			break;
		case THEREMINI_IMPORT_SUM:
		case THEREMINI_IMPORT_IDENTITY:
			/* deliberately unchecked, exactly as the perl leaves it: a dump
			 * can name a waveform that does not exist. Callers that index
			 * param->values with this must range check. */
			v->number = raw[i];
			break;
		case THEREMINI_IMPORT_TEXT:
			break; /* handled above */
		}
	}

	if (number >= 0) {
		const theremini_param *nr = theremini_param_by_id("_nr");
		if (nr) {
			theremini_value *v = &out->values[theremini_param_index(nr)];
			v->number = number;
			v->present = true;
		}
	}

	return true;
}

const theremini_value *theremini_preset_value(const theremini_preset *preset,
                                              const char *id)
{
	const theremini_param *p = preset ? theremini_param_by_id(id) : NULL;

	if (!p) {
		return NULL;
	}
	return &preset->values[theremini_param_index(p)];
}
