/* Value to wire conversion.
 *
 * This is a deliberate transcription of ThereMaxi::Controller::numeric::value_export
 * from the perl implementation, including its behaviour at the ends of the
 * range, because protocol/golden.json was generated by that code and this has
 * to reproduce it byte for byte. Any change in behaviour has to be a change in
 * the golden vectors first, decided against real hardware.
 *
 * Copyright (C) 2017 Peter Niebling and contributors. GPL-3.0-or-later.
 */

#include "theremini/protocol.h"

#include <math.h>

bool theremini_value_export(const theremini_param *param, double value,
                            theremini_wire *out)
{
	if (!param || !out) {
		return false;
	}

	out->bytes[0] = 0;
	out->bytes[1] = 0;
	out->count = 0;

	switch (param->kind) {
	case THEREMINI_TEXT:
		/* names travel as sysex, not as a controller value */
		return false;

	case THEREMINI_ENUM:
		/* the index goes out unchanged - and unchecked, exactly as perl does
		 * it. Callers are responsible for a value in range. */
		out->bytes[0] = (uint8_t)((int)value & 0x7f);
		out->count = 1;
		return true;

	case THEREMINI_NUMERIC:
		break;
	}

	/* NUMERIC: scale to the wire. Unsigned 14-bit uses the storage divisor (see
	 * protocol.h); everything else scales [min, max] onto the wire maximum.
	 * Rounds to nearest - truncating reads back a step low on the device - and
	 * carries the maximum and the signed centre at full width. Matches the perl
	 * value_export. */
	{
		const bool wide = param->bits == 14;
		const int wire_max = wide ? 0x3fff : 0x7f;

		double scaled;
		if (param->wire_divisor > 0) {
			if (value <= param->min) {
				out->bytes[0] = 0;
				out->count = 1;
				return true;
			}
			scaled = value * param->wire_divisor + 0.5;
		} else {
			const double range = param->max - param->min;
			scaled = (value - param->min) * wire_max / range + 0.5;
		}

		if (scaled < 0) {
			scaled = 0;
		}
		unsigned wire = (unsigned)scaled;
		if (wire > (unsigned)wire_max) {
			wire = (unsigned)wire_max;
		}

		if (wide) {
			out->bytes[0] = (uint8_t)(wire >> 7);
			out->bytes[1] = (uint8_t)(wire & 0x7f);
			out->count = 2;
		} else {
			out->bytes[0] = (uint8_t)(wire & 0x7f);
			out->count = 1;
		}
	}

	return true;
}
