/* Value to wire conversion.
 *
 * This is a deliberate transcription of ThereMaxi::Controller::numeric::value_export
 * from the perl implementation, including its behaviour at the ends of the
 * range, because protocol/golden.json was generated by that code and this has
 * to reproduce it byte for byte. Any change in behaviour has to be a change in
 * the golden vectors first, decided against real hardware.
 *
 * Copyright (C) 2017 Peter Niebling and contributors. GPL-3.0-or-later.
 */

#include "theremini/protocol.h"

#include <math.h>

bool theremini_value_export(const theremini_param *param, double value,
                            theremini_wire *out)
{
	if (!param || !out) {
		return false;
	}

	out->bytes[0] = 0;
	out->bytes[1] = 0;
	out->count = 0;

	switch (param->kind) {
	case THEREMINI_TEXT:
		/* names travel as sysex, not as a controller value */
		return false;

	case THEREMINI_ENUM:
		/* the index goes out unchanged - and unchecked, exactly as perl does
		 * it. Callers are responsible for a value in range. */
		out->bytes[0] = (uint8_t)((int)value & 0x7f);
		out->count = 1;
		return true;

	case THEREMINI_NUMERIC:
		break;
	}

	/* The three shortcuts below come straight from the perl. Note that they
	 * return a single byte even for a 14-bit parameter, which leaves the low
	 * controller at whatever the device had. */
	if (value <= param->min) {
		out->bytes[0] = 0;
		out->count = 1;
		return true;
	}
	if (value == 0 && param->min < 0) {
		out->bytes[0] = 0x40;
		out->count = 1;
		return true;
	}
	if (value >= param->max) {
		out->bytes[0] = 0x7f;
		out->count = 1;
		return true;
	}

	{
		const double span = fabs(param->min) + fabs(param->max);
		const int wide = param->bits == 14;
		const double scale = wide ? 0x3fff : 0x7f;

		double scaled = value;
		if (param->min < 0) {
			scaled += fabs(param->min);
		}
		scaled *= scale / span;

		if (scaled > scale) {
			scaled = scale;
		}
		if (scaled < 0) {
			scaled = 0;
		}

		/* perl's >> and & truncate towards zero on the way to an integer */
		const unsigned raw = (unsigned)scaled;

		if (wide) {
			out->bytes[0] = (uint8_t)(raw >> 7);
			out->bytes[1] = (uint8_t)(raw & 0x7f);
			out->count = 2;
		} else {
			out->bytes[0] = (uint8_t)(raw & 0x7f);
			out->count = 1;
		}
	}

	return true;
}
