#!/usr/bin/perl -w

# protocol/golden.json -> a C fixture, so the tests need no JSON parser and no
# runtime dependency at all. Run by CMake at build time.
#
# Usage: tools/generate-c-golden.pl protocol/golden.json output.c

use strict;
use warnings;

use JSON::PP;

my($in,$out) = @ARGV;
die "usage: $0 <golden.json> <output.c>\n" unless $in && $out;

open my $I, '<', $in or die "$in: $!";
my $golden = JSON::PP->new->decode( do { local $/; <$I> } );
close $I;

my $c = <<'HEAD';
/* Generated by tools/generate-c-golden.pl from protocol/golden.json.
 * Do not edit, do not commit. */

#include "golden.h"

const golden_export golden_exports[] = {
HEAD

my $n = 0;
for my $id ( sort keys %{$golden->{export}} )
{
	for my $case ( @{$golden->{export}->{$id}} )
	{
		my @wire = @{$case->{wire}};
		$c .= sprintf "\t{ \"%s\", %.17g, { %d, %d }, %d },\n",
			$id, $case->{value},
			$wire[0], ( @wire > 1 ? $wire[1] : 0 ), scalar @wire;
		$n++;
	}
}

$c .= "};\n\n";
$c .= "const size_t golden_export_count = $n;\n";

open my $O, '>', $out or die "$out: $!";
print $O $c;
close $O;

printf "%s: %d export vectors\n", $out, $n;
