#!/usr/bin/perl -w

# protocol/tables.json -> the LV2 plugin's port description (theremini.ttl) and
# the matching C port table (lv2_ports.h). Generating both from the same source
# keeps the port indices, ranges and units in step with the parameters and with
# each other. Run by CMake at build time.
#
# Usage: tools/generate-lv2.pl tables.json out.ttl out_ports.h

use strict;
use warnings;

use JSON::PP;

my($in,$ttl_out,$hdr_out) = @ARGV;
die "usage: $0 <tables.json> <out.ttl> <out.h>\n" unless $in && $ttl_out && $hdr_out;

open my $I, '<', $in or die "$in: $!";
my $tables = JSON::PP->new->decode( do { local $/; <$I> } );
close $I;

my $URI = 'https://github.com/gunterkoenigsmann/theremaxi/lv2/theremini';

# a parameter is a control port when it is an actual CC with a numeric or enum
# value; names and the preset number are not ports.
my @ports = sort { $a <=> $b } grep { /^\d+$/ } keys %{$tables->{controllers}};

sub symbol
{
	my($e) = @_;
	( my $s = lc $e->{name} ) =~ s/[^a-z0-9]+/_/g;
	$s =~ s/^_+|_+$//g;
	"${s}_$e->{cc}"; # the cc keeps it unique and stable
}

sub unit
{
	my($fmt) = @_;
	return 'units:pc'       if $fmt && $fmt =~ /%%/;
	return 'units:hz'       if $fmt && $fmt =~ /Hz/;
	return 'units:ms'       if $fmt && $fmt =~ /ms/;
	return 'units:semitone12TET' if $fmt && $fmt =~ /Semitone/;
	undef;
}


# --------------------------------------------------------------- theremini.ttl

my $ttl = <<"HEAD";
\@prefix lv2:   <http://lv2plug.in/ns/lv2core#> .
\@prefix atom:  <http://lv2plug.in/ns/ext/atom#> .
\@prefix midi:  <http://lv2plug.in/ns/ext/midi#> .
\@prefix urid:  <http://lv2plug.in/ns/ext/urid#> .
\@prefix units: <http://lv2plug.in/ns/extensions/units#> .
\@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
\@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
\@prefix doap:  <http://usefulinc.com/ns/doap#> .

# Generated by tools/generate-lv2.pl. Do not edit.

<$URI>
	a lv2:Plugin , lv2:MIDIPlugin ;
	doap:name "ThereMaxi" ;
	doap:license <https://www.gnu.org/licenses/gpl-3.0.html> ;
	lv2:requiredFeature urid:map ;
	lv2:optionalFeature lv2:hardRTCapable ;
HEAD

my @port_ttl;
my $index = 0;
for my $cc ( @ports )
{
	my $e = $tables->{controllers}->{$cc};
	my $sym = symbol($e);
	my $min = $e->{min} // 0;
	my $max = $e->{max} // ( $e->{values} ? $#{$e->{values}} : 127 );

	my $p = "\t[\n";
	$p .= "\t\ta lv2:InputPort , lv2:ControlPort ;\n";
	$p .= "\t\tlv2:index $index ;\n";
	$p .= "\t\tlv2:symbol \"$sym\" ;\n";
	$p .= "\t\tlv2:name \"$e->{name}\" ;\n";
	$p .= sprintf "\t\tlv2:minimum %s ;\n\t\tlv2:maximum %s ;\n\t\tlv2:default %s ;\n",
		$min, $max, $min;

	if ( $e->{values} )
	{
		$p .= "\t\tlv2:portProperty lv2:integer , lv2:enumeration ;\n";
		my @sp;
		for my $i ( 0 .. $#{$e->{values}} )
		{
			( my $label = $e->{values}->[$i] ) =~ s/"/\\"/g;
			push @sp, "\t\t\t[ rdfs:label \"$label\" ; rdf:value $i ]";
		}
		$p .= "\t\tlv2:scalePoint\n".join(" ,\n",@sp)." ;\n";
	}

	if ( my $u = unit($e->{format}) )
	{
		$p .= "\t\tunits:unit $u ;\n";
	}
	$p .= "\t]";
	push @port_ttl, $p;
	$index++;
}

# the MIDI output
push @port_ttl, join '',
	"\t[\n",
	"\t\ta lv2:OutputPort , atom:AtomPort ;\n",
	"\t\tatom:bufferType atom:Sequence ;\n",
	"\t\tatom:supports midi:MidiEvent ;\n",
	"\t\tlv2:index $index ;\n",
	"\t\tlv2:symbol \"midi_out\" ;\n",
	"\t\tlv2:name \"MIDI Out\" ;\n",
	"\t]";

$ttl .= "\tlv2:port\n".join(" ,\n",@port_ttl)." .\n";

open my $T, '>', $ttl_out or die "$ttl_out: $!";
print $T $ttl;
close $T;


# ----------------------------------------------------------------- lv2_ports.h

my $control = scalar @ports;
my $hdr = <<"HEAD";
/* Generated by tools/generate-lv2.pl from protocol/tables.json.
 * Do not edit, do not commit. The port indices here match theremini.ttl. */

#ifndef THEREMINI_LV2_PORTS_H
#define THEREMINI_LV2_PORTS_H

#define THEREMINI_LV2_URI "$URI"
#define THEREMINI_LV2_CONTROL_PORTS $control
#define THEREMINI_LV2_MIDI_OUT_PORT $control

/* Port index -> parameter id, in the same order as theremini.ttl. */
static const char *const theremini_lv2_port_param[THEREMINI_LV2_CONTROL_PORTS] = {
HEAD
$hdr .= "\t\"$_\",\n" for @ports;
$hdr .= "};\n\n#endif\n";

open my $H, '>', $hdr_out or die "$hdr_out: $!";
print $H $hdr;
close $H;

printf "%s, %s: %d control ports\n", $ttl_out, $hdr_out, $control;
