#!/usr/bin/perl -w

# protocol/golden.json -> a C fixture, so the tests need no JSON parser and no
# runtime dependency at all. Run by CMake at build time.
#
# Usage: tools/generate-c-golden.pl protocol/golden.json output.c

use strict;
use warnings;

use JSON::PP;
use MIME::Base64;

my($in,$out) = @ARGV;
die "usage: $0 <golden.json> <output.c>\n" unless $in && $out;

open my $I, '<', $in or die "$in: $!";
my $golden = JSON::PP->new->decode( do { local $/; <$I> } );
close $I;

my $c = <<'HEAD';
/* Generated by tools/generate-c-golden.pl from protocol/golden.json.
 * Do not edit, do not commit. */

#include "golden.h"

const golden_export golden_exports[] = {
HEAD

my $n = 0;
for my $id ( sort keys %{$golden->{export}} )
{
	for my $case ( @{$golden->{export}->{$id}} )
	{
		my @wire = @{$case->{wire}};
		$c .= sprintf "\t{ \"%s\", %.17g, { %d, %d }, %d },\n",
			$id, $case->{value},
			$wire[0], ( @wire > 1 ? $wire[1] : 0 ), scalar @wire;
		$n++;
	}
}

$c .= "};\n\n";
$c .= "const size_t golden_export_count = $n;\n\n";

# decoded preset dumps: the raw bytes, and what perl made of them
my $presets = 0;
my $values = 0;
for my $p ( @{$golden->{presets}} )
{
	my $raw = decode_base64($p->{input});
	$c .= sprintf "static const uint8_t preset_input_%d[] = {\n", $presets;
	my @bytes = map { sprintf '0x%02x', $_ } unpack 'C*', $raw;
	while ( @bytes )
	{
		$c .= "\t".join(', ', splice @bytes, 0, 12).",\n";
	}
	$c .= "};\n\n";

	$c .= sprintf "static const golden_value preset_values_%d[] = {\n", $presets;
	for my $id ( sort keys %{$p->{decoded}} )
	{
		my $v = $p->{decoded}->{$id};
		if ( !defined $v )
		{
			$c .= sprintf "\t{ \"%s\", 0, NULL },\n", $id;
		}
		elsif ( $v =~ /^-?[0-9.]+(?:[eE][-+]?\d+)?$/ )
		{
			$c .= sprintf "\t{ \"%s\", %.17g, NULL },\n", $id, $v;
		}
		else
		{
			( my $esc = $v ) =~ s/(["\\])/\\$1/g;
			$c .= sprintf "\t{ \"%s\", 0, \"%s\" },\n", $id, $esc;
		}
		$values++;
	}
	$c .= "};\n\n";
	$presets++;
}

$c .= "const golden_preset golden_presets[] = {\n";
for my $i ( 0 .. $presets-1 )
{
	my $p = $golden->{presets}->[$i];
	$c .= sprintf "\t{ preset_input_%d, sizeof preset_input_%d, %d, preset_values_%d, sizeof preset_values_%d / sizeof preset_values_%d[0] },\n",
		$i, $i, $i, $i, $i, $i;
}
$c .= "};\n\n";
$c .= "const size_t golden_preset_count = $presets;\n\n";

# the seven-bit unpacking, on its own
$c .= "const golden_sx golden_sx_vectors[] = {\n";
my $sx = 0;
for my $v ( @{$golden->{sx}} )
{
	$c .= sprintf "\t{ { %d, %d, %d }, %d },\n",
		$v->{in}->[0], $v->{in}->[1], $v->{in}->[2], $v->{out};
	$sx++;
}
$c .= "};\n\n";
$c .= "const size_t golden_sx_count = $sx;\n\n";

# whole framed dumps, and the numeric values each preset decoded to
my $messages = 0;
my $mvalues = 0;
for my $m ( @{$golden->{messages}} )
{
	my $raw = decode_base64($m->{input});
	$c .= sprintf "static const uint8_t message_input_%d[] = {\n", $messages;
	my @bytes = map { sprintf '0x%02x', $_ } unpack 'C*', $raw;
	while ( @bytes )
	{
		$c .= "\t".join(', ', splice @bytes, 0, 12).",\n";
	}
	$c .= "};\n\n";

	my $np = 0;
	for my $p ( @{$m->{presets}} )
	{
		$c .= sprintf "static const golden_value message_%d_preset_%d[] = {\n", $messages, $np;
		for my $id ( sort keys %$p )
		{
			my $v = $p->{$id};
			next unless defined $v && $v =~ /^-?[0-9.]+(?:[eE][-+]?\d+)?$/;
			$c .= sprintf "\t{ \"%s\", %.17g, NULL },\n", $id, $v;
			$mvalues++;
		}
		$c .= "};\n\n";
		$np++;
	}

	$c .= sprintf "static const golden_message_preset message_%d_presets[] = {\n", $messages;
	for my $i ( 0 .. $np-1 )
	{
		$c .= sprintf "\t{ message_%d_preset_%d, sizeof message_%d_preset_%d / sizeof message_%d_preset_%d[0] },\n",
			$messages, $i, $messages, $i, $messages, $i;
	}
	$c .= "};\n\n";
	$messages++;
}

$c .= "const golden_message golden_messages[] = {\n";
for my $i ( 0 .. $messages-1 )
{
	my $np = scalar @{$golden->{messages}->[$i]->{presets}};
	$c .= sprintf "\t{ message_input_%d, sizeof message_input_%d, message_%d_presets, %d },\n",
		$i, $i, $i, $np;
}
$c .= "};\n\n";
$c .= "const size_t golden_message_count = $messages;\n";

open my $O, '>', $out or die "$out: $!";
print $O $c;
close $O;

printf "%s: %d export vectors, %d presets, %d sx pairs, %d messages\n",
	$out, $n, $presets, $sx, $messages;
