#!/usr/bin/perl -w

# protocol/tables.json -> C. Run by CMake at build time; the result is never
# committed, so the generated tables cannot drift from the JSON, which in turn
# cannot drift from lib/ (t/check.sh enforces that half).
#
# Usage: tools/generate-c-tables.pl protocol/tables.json output.c

use strict;
use warnings;

use JSON::PP;

my($in,$out) = @ARGV;
die "usage: $0 <tables.json> <output.c>\n" unless $in && $out;

open my $I, '<', $in or die "$in: $!";
my $tables = JSON::PP->new->decode( do { local $/; <$I> } );
close $I;

sub cstr { my($s) = @_; return 'NULL' unless defined $s; $s =~ s/([\\"])/\\$1/g; qq("$s") }

my @ids = sort keys %{$tables->{controllers}};

my $c = <<"HEAD";
/* Generated by tools/generate-c-tables.pl from protocol/tables.json.
 * Do not edit, do not commit. */

#include "theremini/protocol.h"
#include "internal.h"

#include <string.h>

HEAD

# enum label tables
for my $id ( @ids )
{
	my $e = $tables->{controllers}->{$id};
	next unless $e->{values};
	( my $sym = $id ) =~ s/\W/_/g;
	$c .= sprintf "static const char *const values_%s[] = {\n", $sym;
	$c .= sprintf "\t%s,\n", cstr($_) for @{$e->{values}};
	$c .= "};\n\n";
}

$c .= "static const theremini_param params[] = {\n";
for my $id ( @ids )
{
	my $e = $tables->{controllers}->{$id};
	( my $sym = $id ) =~ s/\W/_/g;

	my $kind = $e->{values}                  ? 'THEREMINI_ENUM'
	         : defined $e->{min}             ? 'THEREMINI_NUMERIC'
	         :                                 'THEREMINI_TEXT';

	$c .= "\t{\n";
	$c .= sprintf "\t\t.id = %s, .name = %s, .kind = %s,\n", cstr($id), cstr($e->{name}), $kind;
	$c .= sprintf "\t\t.cc = %s, .lsb_cc = %s, .bits = %d,\n",
		( $id =~ /^\d+$/ ? $id : -1 ),
		( defined $e->{lsb_cc} ? $e->{lsb_cc} : -1 ),
		( $e->{bits} || 7 );
	$c .= sprintf "\t\t.min = %.17g, .max = %.17g, .digits = %d, .format = %s,\n",
		( defined $e->{min} ? $e->{min} : 0 ),
		( defined $e->{max} ? $e->{max} : 0 ),
		( defined $e->{dig} ? $e->{dig} : 0 ),
		cstr($e->{format});
	$c .= sprintf "\t\t.values = %s, .value_count = %d,\n",
		( $e->{values} ? "values_$sym" : 'NULL' ),
		( $e->{values} ? scalar @{$e->{values}} : 0 );
	$c .= sprintf "\t\t.in_preset = %s, .import = %s,\n",
		( $e->{in_preset} ? 'true' : 'false' ),
		'THEREMINI_IMPORT_'.uc($e->{import});
	$c .= sprintf "\t\t.tab = %s, .group = %s, .label = %s, .order = %d,\n",
		cstr($e->{ui} ? $e->{ui}->{tab}   : undef),
		cstr($e->{ui} ? $e->{ui}->{group} : undef),
		cstr($e->{ui} && $e->{ui}->{label} ? $e->{ui}->{label} : $e->{name}),
		( $e->{ui} ? $e->{ui}->{order} : 0 );
	$c .= "\t},\n";
}
$c .= "};\n\n";

# how a preset dump is taken apart
my %PACK =
(
	'S'        => 'THEREMINI_PACK_U16',
	'v'        => 'THEREMINI_PACK_U16',
	's'        => 'THEREMINI_PACK_S16',
	'(Zx)13'   => 'THEREMINI_PACK_TEXT_PADDED',
	'Z13'      => 'THEREMINI_PACK_TEXT',
);

$c .= "static const theremini_offset offsets[] = {\n";
for my $off ( sort { hex($a) <=> hex($b) } keys %{$tables->{sysex}->{offsets}} )
{
	my $o = $tables->{sysex}->{offsets}->{$off};
	my $pack = $PACK{ $o->{pack} } or die "unknown pack template '$o->{pack}' at $off\n";
	$c .= sprintf "\t{ %s, %s, %s, %.17g },\n",
		$off, cstr($o->{cc}), $pack,
		( defined $o->{divisor} ? $o->{divisor} : 0 );
}
$c .= "};\n\n";

# the fixed bytes of the device control messages
sub bytes_array
{
	my($name,@bytes) = @_;
	sprintf "static const uint8_t %s[] = { %s };\n", $name,
		join ', ', map { sprintf '0x%02x', $_ } @bytes;
}
$c .= bytes_array('msg_identity_request',    @{$tables->{messages}->{identity_request}});
$c .= bytes_array('msg_request_all_presets', @{$tables->{messages}->{request_all_presets}});
$c .= bytes_array('msg_preset_name_prefix',  @{$tables->{name_messages}->{write_preset_name}->{prefix}});
$c .= bytes_array('msg_preset_name_suffix',  @{$tables->{name_messages}->{write_preset_name}->{suffix}});
$c .= bytes_array('msg_effect_name_prefix',  @{$tables->{name_messages}->{write_effect_name}->{prefix}});
$c .= bytes_array('msg_effect_name_suffix',  @{$tables->{name_messages}->{write_effect_name}->{suffix}});
$c .= "\n";

$c .= <<'TAIL';
const theremini_param *theremini_params(size_t *count)
{
	if (count) {
		*count = sizeof params / sizeof params[0];
	}
	return params;
}

const theremini_param *theremini_param_by_id(const char *id)
{
	if (!id) {
		return NULL;
	}
	for (size_t i = 0; i < sizeof params / sizeof params[0]; i++) {
		if (strcmp(params[i].id, id) == 0) {
			return &params[i];
		}
	}
	return NULL;
}

const theremini_param *theremini_param_by_cc(int cc)
{
	for (size_t i = 0; i < sizeof params / sizeof params[0]; i++) {
		if (params[i].cc == cc) {
			return &params[i];
		}
	}
	return NULL;
}

const theremini_offset *theremini_offsets(size_t *count)
{
	if (count) {
		*count = sizeof offsets / sizeof offsets[0];
	}
	return offsets;
}

size_t theremini_param_index(const theremini_param *param)
{
	return (size_t)(param - params);
}

/* The message templates, for message.c. Declared in internal.h. */
#define TEMPLATE(fn, arr) \
	const uint8_t *fn(size_t *len) { if (len) *len = sizeof arr; return arr; }
TEMPLATE(theremini_tmpl_identity_request,    msg_identity_request)
TEMPLATE(theremini_tmpl_request_all_presets, msg_request_all_presets)
TEMPLATE(theremini_tmpl_preset_name_prefix,  msg_preset_name_prefix)
TEMPLATE(theremini_tmpl_preset_name_suffix,  msg_preset_name_suffix)
TEMPLATE(theremini_tmpl_effect_name_prefix,  msg_effect_name_prefix)
TEMPLATE(theremini_tmpl_effect_name_suffix,  msg_effect_name_suffix)
#undef TEMPLATE
TAIL

open my $O, '>', $out or die "$out: $!";
print $O $c;
close $O;
